# Generated by Django 3.2.3 on 2021-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0002_alter_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='insurance_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='insurance_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='licence_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='licence_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='vehile_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
