# Generated by Django 3.2.4 on 2021-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0004_auto_20210602_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_plate', models.FileField(upload_to='plate')),
            ],
        ),
        migrations.CreateModel(
            name='user_nuberplate_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
