# Generated by Django 3.2.4 on 2021-06-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0005_number_plate_user_nuberplate_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number_plate',
            options={'verbose_name': 'Number_plate', 'verbose_name_plural': 'Number_plates'},
        ),
    ]
