# Generated by Django 3.2.4 on 2021-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0006_alter_number_plate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pollution_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='reg_expiry',
            field=models.DateField(null=True),
        ),
    ]
