# Generated by Django 3.2.4 on 2021-06-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0008_rename_reg_expiry_userdetails_registration_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='registration_expiry',
            new_name='registrio_expiry',
        ),
    ]
