# Generated by Django 3.2.4 on 2021-06-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0009_rename_registration_expiry_userdetails_registrio_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='pollution_expiry',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='registrio_expiry',
        ),
    ]
