# Generated by Django 3.2.4 on 2021-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0010_auto_20210612_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pollution_expiry',
            field=models.DateField(null=True),
        ),
    ]
