# Generated by Django 3.2.4 on 2021-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0011_userdetails_pollution_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pollution_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
