# Generated by Django 3.2.4 on 2021-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0012_userdetails_pollution_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='registration_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='registration_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
