# Generated by Django 3.2.4 on 2021-06-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0014_rename_registration_expiry_userdetails_reg_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='reg_expiry',
            new_name='registrio_expiry',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='pollution_number',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='registration_number',
        ),
    ]
