# Generated by Django 3.2.4 on 2021-06-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0015_auto_20210612_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='pollution_expiry',
        ),
    ]
