# Generated by Django 3.2.4 on 2021-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0016_remove_userdetails_pollution_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='registrio_expiry',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pollution_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
