# Generated by Django 3.2.4 on 2021-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0017_auto_20210612_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pollution_expiry',
            field=models.DateField(null=True),
        ),
    ]
