# Generated by Django 3.2.4 on 2021-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0019_auto_20210612_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='true_of_birth',
            field=models.DateField(null=True),
        ),
    ]
