# Generated by Django 3.2.4 on 2021-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0020_userdetails_true_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='true_of_birth',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='in_expiry',
            field=models.DateField(null=True),
        ),
    ]
