# Generated by Django 3.2.4 on 2021-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0021_auto_20210612_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='i_expiry',
            field=models.DateField(null=True),
        ),
    ]
