# Generated by Django 3.2.4 on 2021-06-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0022_userdetails_i_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='i_expiry',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='in_expiry',
        ),
    ]
