# Generated by Django 3.2.4 on 2021-06-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0023_auto_20210612_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='pollution_expiry',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='pollution_number',
        ),
    ]
