# Generated by Django 3.2.4 on 2021-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0024_auto_20210612_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pollution_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pollution_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
